version: '3.9'

services:
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=boamsmar2022customerdb
    volumes:
      - /data/mysql
    healthcheck:        
        interval: 30s
        timeout: 10s
        retries: 5
  
  redis:
    image: redis 

  user-app:
    image: userapp
    build:
      context: ./
      dockerfile: dockerfile
    depends_on:
      - mysql
      - redis
    deploy:
      resources:
          limits:
             cpus: '0.50'
             memory: 512M
          reservations:
             cpus: '0.25'
             memory: 256M   
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 15
        window: 50s
    ports:
       #- 8060-8070:7070
        - 7074:7070
    volumes:
      - /data/compose-app

  